#ifndef __ZED_RENDERER_GLRENDERTYPES_HPP__
#define __ZED_RENDERER_GLRENDERTYPES_HPP__

typedef struct __ZED_SHADER_VERTEXATTRIBUTE_GL : __ZED_SHADER_VERTEXATTRIBUTE
{
	char			*pName;
}ZED_SHADER_VERTEXATTRIBUTE_GL;

typedef struct __ZED_GLVERSION
{
	ZED_SINT32	Major;
	ZED_SINT32	Minor;
}ZED_GLVERSION;

typedef GLenum ZED_RENDERPRIMITIVETYPE;

const GLenum	ZED_TRIANGLE_LIST	= GL_TRIANGLES;
const GLenum	ZED_TRIANGLE_FAN	= GL_TRIANGLE_FAN;
const GLenum	ZED_TRIANGLE_STRIP	= GL_TRIANGLE_STRIP;
const GLenum	ZED_POINTS			= GL_POINTS;
const GLenum	ZED_LINE_LIST		= GL_LINES;
const GLenum	ZED_LINE_STRIP		= GL_LINE_STRIP;
const GLenum	ZED_LINE_LOOP		= GL_LINE_LOOP;

#endif

