#! /bin/sh
#Tag 0x00270237

MAYA_LOCATION=${MAYA_LOCATION:="/usr/aw/maya6.0"}

case `uname` in
    IRIX*)
		LDCMD=CC
		WARNFLAGS="-Wl,-woff,84 -Wl,-woff,85"
		LDFLAGS="${WARNFLAGS}"
		LIBS="\
		  -L${MAYA_LOCATION}/lib \
		  -L/usr/lib32/internal \
		  -lOpenMayalib \
		  -lOpenMaya \
		  -lOpenMayaAnim \
		  -lOpenMayaFX \
		  -lOpenMayaUI \
		  -lOpenMayaRender \
		  -lAnimSlice \
		  -lDeformSlice \
		  -lDynSlice \
		  -lKinSlice \
		  -lModelSlice \
		  -lNurbsSlice \
		  -lPolySlice \
		  -lProjectSlice \
		  -lImage \
		  -lShared \
		  -lTranslators \
		  -lDataModel \
		  -lRenderModel \
		  -lNurbsEngine \
		  -lDependEngine \
		  -lCommandEngine \
		  -lFoundation \
		  -lStringCatalog \
		  -lStackTrace \
		  -lm \
		  -lcl \
		  -lfpe "
		;;

    Linux*)
		LDCMD=gcc
		WARNFLAGS=
		LDFLAGS="${WARNFLAGS} -Wl,-rpath ${MAYA_LOCATION}/lib"
		LIBS="-L${MAYA_LOCATION}/lib \
		  -lOpenMayalib \
		  -lOpenMaya \
		  -lOpenMayaAnim \
		  -lOpenMayaFX \
		  -lOpenMayaUI \
		  -lOpenMayaRender \
		  -lAnimSlice \
		  -lDeformSlice \
		  -lDynSlice \
		  -lKinSlice \
		  -lModelSlice \
		  -lNurbsSlice \
		  -lPolySlice \
		  -lProjectSlice \
		  -lImage \
		  -lShared \
		  -lTranslators \
		  -lDataModel \
		  -lRenderModel \
		  -lNurbsEngine \
		  -lDependEngine \
		  -lCommandEngine \
		  -lFoundation \
		  -lStringCatalog \
		  -lGLU \
		  -lGL \
		  -lHWGL \
		  -lstdc++ \
		  -lm -ldl"
		;;
esac

${LDCMD}  -Wno-deprecated -D_BOOL -DLINUX -I/usr/aw/maya6.0/include ${LDFLAGS} $* ${LIBS}
