#ifndef __ZED_SYSTEM_INPUTTYPES_HPP__
#define __ZED_SYSTEM_INPUTTYPES_HPP__

#include <System/DataTypes.hpp>

// Gamepad controls
typedef enum __ZED_GAMEPAD
{
	ZED_GAMEPAD_LTRIGGER,
	ZED_GAMEPAD_RTRIGGER,

	ZED_GAMEPAD_LSTICKX,
	ZED_GAMEPAD_LSTICKY,

	ZED_GAMEPAD_RSTICKX,
	ZED_GAMEPAD_RSTICKY,
	
	// Dreamcast:	[Disabled], [Disabled]
	ZED_GAMEPAD_LSTICK_BUTTON,
	ZED_GAMEPAD_RSTICK_BUTTON,
	
	// Dreamcast:	Start, [Disabled]
	ZED_GAMEPAD_START,
	ZED_GAMEPAD_BACK,
	
	// Xbox (360):	D-Pad
	// Dreamcast:	D-Pad
	ZED_GAMEPAD_LPAD_UP,
	ZED_GAMEPAD_LPAD_DOWN,
	ZED_GAMEPAD_LPAD_LEFT,
	ZED_GAMEPAD_LPAD_RIGHT,

	// Xbox (360):	Y, A, X, B
	// Dreamcast:	Y, A, X, B
	ZED_GAMEPAD_RPAD_UP,
	ZED_GAMEPAD_RPAD_DOWN,
	ZED_GAMEPAD_RPAD_LEFT,
	ZED_GAMEPAD_RPAD_RIGHT,

	// Xbox:		White, Black
	// Xbox 360:	L-Bumper, R-Bumper
	// Dreamcast:	Disabled
	ZED_GAMEPAD_LSHOULDER,
	ZED_GAMEPAD_RSHOULDER,
}ZED_GAMEPAD;

typedef enum __ZED_KEY
{
	ZED_KEY_TAB					= 9,
	ZED_KEY_ENTER				= 13,
	ZED_KEY_ESCAPE				= 27,
	ZED_KEY_SPACE				= 32,

	ZED_KEY_A					= 40,
	ZED_KEY_B,
	ZED_KEY_C,
	ZED_KEY_D,
	ZED_KEY_E,
	ZED_KEY_F,
	ZED_KEY_G,
	ZED_KEY_H,
	ZED_KEY_I,
	ZED_KEY_J,
	ZED_KEY_K,
	ZED_KEY_L,
	ZED_KEY_M,
	ZED_KEY_N,
	ZED_KEY_O,
	ZED_KEY_P,
	ZED_KEY_Q,
	ZED_KEY_R,
	ZED_KEY_S,
	ZED_KEY_T,
	ZED_KEY_U,
	ZED_KEY_V,
	ZED_KEY_W,
	ZED_KEY_X,
	ZED_KEY_Y,
	ZED_KEY_Z,

	ZED_KEY_BACKSPACE			= 127,

	ZED_KEY_COMMAND				= 128,
	ZED_KEY_CAPSLOCK,
	ZED_KEY_SCROLLLOCK,
	ZED_KEY_POWER,
	ZED_KEY_PAUSE,

	ZED_KEY_UPARROW				= 133,
	ZED_KEY_DOWNARROW,
	ZED_KEY_LEFTARROW,
	ZED_KEY_RIGHTARROW,

	ZED_KEY_LSUPER				= 137,
	ZED_KEY_RSUPER,
	ZED_KEY_SUPER,

	ZED_KEY_ALT					= 140,
	ZED_KEY_CTRL,
	ZED_KEY_SHIFT,
	ZED_KEY_INS,
	ZED_KEY_DEL,
	ZED_KEY_PGDN,
	ZED_KEY_PGUP,
	ZED_KEY_HOME,
	ZED_KEY_END,

	ZED_KEY_F1					= 149,
	ZED_KEY_F2,
	ZED_KEY_F3,
	ZED_KEY_F4,
	ZED_KEY_F5,
	ZED_KEY_F6,
	ZED_KEY_F7,
	ZED_KEY_F8,
	ZED_KEY_F9,
	ZED_KEY_F10,
	ZED_KEY_F11,
	ZED_KEY_F12,
	ZED_KEY_INVERSE_EXCLAMATION	= 161,
	ZED_KEY_F13,
	ZED_KEY_F14,
	ZED_KEY_F15,

	ZED_KEY_NP_HOME				= 165,
	ZED_KEY_NP_UPARROW,
	ZED_KEY_NP_PGUP,
	ZED_KEY_NP_LEFTARROW,
	ZED_KEY_NP_5,
	ZED_KEY_NP_RIGHTARROW,
	ZED_KEY_NP_END,
	ZED_KEY_NP_DOWNARROW,
	ZED_KEY_NP_PGDN,
	ZED_KEY_NP_ENTER,
	ZED_KEY_NP_INS,
	ZED_KEY_NP_DEL,
	ZED_KEY_NP_SLASH,
	ZED_KEY_SUPERSCRIPT_TWO		= 178,
	ZED_KEY_NP_MINUS,
	ZED_KEY_ACUTE_ACCENT		= 180,
	ZED_KEY_NP_PLUS,
	ZED_KEY_NP_NUMLOCK,
	ZED_KEY_NP_ASTERISK,
	ZED_KEY_NP_EQUALS,
}ZED_KEY;

typedef struct __ZED_KEYSTROKE
{
	ZED_BYTE	Key;
	ZED_BYTE	Flags;
	ZED_CHAR8	ASCII;
	ZED_BYTE	__Padding;
}ZED_KEYSTROKE;

typedef struct __ZED_KEYBOARDSTATE
{
	char	Key[ 256 ];
}ZED_KEYBOARDSTATE;

typedef enum __ZED_MOUSE_BUTTON
{
	ZED_MOUSE_BUTTON_1 = 1 << 0,
	ZED_MOUSE_BUTTON_2 = 1 << 1,
	ZED_MOUSE_BUTTON_3 = 1 << 2,
	ZED_MOUSE_BUTTON_4 = 1 << 3,
	ZED_MOUSE_BUTTON_5 = 1 << 4,
	ZED_MOUSE_BUTTON_6 = 1 << 5,
	ZED_MOUSE_BUTTON_7 = 1 << 6,
	ZED_MOUSE_BUTTON_8 = 1 << 7,
	ZED_MOUSE_BUTTON_9 = 1 << 8,
	ZED_MOUSE_BUTTON_10 = 1 << 9,
	ZED_MOUSE_BUTTON_11 = 1 << 10,
	ZED_MOUSE_BUTTON_12 = 1 << 11,
	ZED_MOUSE_BUTTON_13 = 1 << 12,
	ZED_MOUSE_BUTTON_14 = 1 << 13,
	ZED_MOUSE_BUTTON_15 = 1 << 14,
	ZED_MOUSE_BUTTON_16 = 1 << 15,
	ZED_MOUSE_BUTTON_17 = 1 << 16,
	ZED_MOUSE_BUTTON_18 = 1 << 17,
	ZED_MOUSE_BUTTON_19 = 1 << 18,
	ZED_MOUSE_BUTTON_20 = 1 << 19,
	ZED_MOUSE_BUTTON_21 = 1 << 20,
	ZED_MOUSE_BUTTON_22 = 1 << 21,
	ZED_MOUSE_BUTTON_23 = 1 << 22,
	ZED_MOUSE_BUTTON_24 = 1 << 23,
	ZED_MOUSE_BUTTON_25 = 1 << 24,
	ZED_MOUSE_BUTTON_26 = 1 << 25,
	ZED_MOUSE_BUTTON_27 = 1 << 26,
	ZED_MOUSE_BUTTON_28 = 1 << 27,
	ZED_MOUSE_BUTTON_29 = 1 << 28,
	ZED_MOUSE_BUTTON_30 = 1 << 29,
	ZED_MOUSE_BUTTON_31 = 1 << 30,
	ZED_MOUSE_BUTTON_32 = 1 << 31
}ZED_MOUSE_BUTTON;

typedef enum __ZED_MOUSE_AXIS
{
	ZED_MOUSE_COORDINATE_X,
	ZED_MOUSE_COORDINATE_Y
}ZED_MOUSE_AXIS;

typedef struct __ZED_MOUSE_COORDINATE
{
	ZED_SINT32	X;
	ZED_SINT32	Y;
}ZED_MOUSE_COORDINATE;

typedef struct __INPUT_LIST
{
	// Only one mouse and keyboard are supported
	ZED_BOOL	Keyboard;
	ZED_BOOL	Mouse;
	// Gamepads can be lightguns, controllers, wheels, and fishing rods
	ZED_BYTE	Gamepads;
	ZED_BYTE	MemoryUnits;
}INPUT_LIST, *LPINPUT_LIST;

typedef struct __ZED_MOUSE_STATE
{
	ZED_MOUSE_COORDINATE	Coordinate;
	ZED_MOUSE_BUTTON		Buttons;
}ZED_MOUSE_STATE;

const ZED_UINT32 ZED_INPUT_DEVICE_KEYBOARD	= 0x00000001;
const ZED_UINT32 ZED_INPUT_DEVICE_MOUSE		= 0x00000002;
const ZED_UINT32 ZED_INPUT_DEVICE_GAMEPAD	= 0x00000004;

namespace ZED
{
	namespace System
	{
		ZED_CHAR8 *KeyToString( const ZED_KEY p_Key );
	}
}

#endif

